### ISSUE TITLE
Consent Form - Making the course modules toggling UX clearer?

### ISSUE THREAD

**Issue by acquaalta** [academic-moodle-cooperation/moodle-mod_consentform#10]
Hi,
When a teacher want to mark/check a course module (activity/resource) in the plugin, all that is needed is checking the checkbox of the module.
I was surprised when I found out that change is saved even without clicking a "Save changes" button. Is it intentional?

Thanks

**Comment by goggo24** [comment]
Also in moodle core plugins the "save changes" button is now replaced by autosave - e.g. options in assignment. Therefore we implemented it in our plugins too. Is it confusing as a teacher or are you just not used to it?

**Comment by acquaalta** [comment]
Hi,
1. What do you mean by 'Also in moodle core plugins the "save changes" button is now replaced by autosave'? Your plugin is the first one that I saw in this method. Do you have a reference/page that deals with this change in Moodl core plugins? That's interesting.

2. I think it's more than I not used to it. It confused some of my colleagues too.

Thanks

**Comment by acquaalta** [comment]
Hi @goggo24,
In case you missed my response from Sep 2023, I'm replying here again.
Thanks even just for reading it.

**Comment by bluetom** [comment]
Hi,
in moodle you have the course main page where most of the actions in edit mode take effect instantly without buttons or confirmation windows. On the other hand you have lists like the participants list where you can check participants one by one and then define the action to take on the selected entries.
I would say the course module list is nearer to the course view-page than to the participants list and so it is quite logical to use the same saving technique. And within seconds the module is painted red (or grey) and the user sees what happens.
And what is the worst case? That the user didn't want to check (uncheck) the module. Than he just click the module again!

**Comment by acquaalta** [comment]
Hi @bluetom,
OK, a valid point and in any case you're the boss. It's your plugin 😃 
Thanks for this wonderful plugin.
